#+title: Great Basin Session (22 January 2023)
#+date: 2023-01-22
#+filetags: :session:

* Session Recapitulation

When we last ventured to the Great Basin...

The members of the Task Force and their allies where in a dire situation. After
breaking into a remote monastery in the Niven Imperium to slay Keburipemi, one
of the Harbingers of The Shattering and the current leader of the largest crime
syndicate in the Basin, you engaged the monks and sages on the first floor of
the temple. In quick succession, [[https://aonprd.com/SpellDisplay.aspx?ItemName=Obsidian+Flow][Obsidian Flow]] and [[https://aonprd.com/SpellDisplay.aspx?ItemName=Firefall][Firefall]] caused most of the
task force to become bound, blind and burning. Amidst the chaos, Oisin's body
fell to the floor from the ceiling.

With both sides reeling from the effects of Firefall (including the monks who
were all hit with friendly fire and blinded themselves), Niwa struck down one of
the sages. This action further disrupted the recover on the monk's side and
widened the slim chance of opportunity that had been presented to the Task
Force. Coupled with numerous channel energy discharges from Jusa, you were able
to find your footing and push back on the onslaught.

Notable highlights from the ensuing melee included:
- Zorro casting [[https://aonprd.com/SpellDisplay.aspx?ItemName=Aqueous%20Orb][Aqueous Orb]] to extinguish some of the nearby braziers and
  scoop up several of the monks, dragging them across the monastery and
  eventually knocking them unconscious.
- Jusa, while blinded and entangled in obsidian, functioning as life
  support for most of the Task Force with penalty of channel positive energy
  discharges.
- The enemy sage casting [[https://aonprd.com/SpellDisplay.aspx?ItemName=Wall%20of%20Fire][Wall of Fire]], encircling all of the still bound task
  force members.
- Meru dispelling the Wall of Fire the round before it would have killed Redfern.
- A last ditch attempt by the remaining sage to cast an [[https://aonprd.com/FeatDisplay.aspx?ItemName=Apocalyptic%20Spell][Apocalyptic]] [[https://aonprd.com/SpellDisplay.aspx?ItemName=Fireball][Fireball]].

Eventually, you prevailed through strong teamwork and supporting one another.
All of the sages where slain and all but one of the monks were disposed of. Meru
negotiated with the last monk, bargaining on the name of his dead lord that in
exchange for his life and freedom he would show you the passage down. He also
mentioned that the figure on the ceiling was likely an Avatar of Keburipemi.
After a performance of a rhythmic dance, a large gate opened in the engraved wall
of a dragon raining destruction upon a village.

We now resume as you enter the caldera of the volcano on the store of a lake of
lava. Before you sit three masked figure, carefully clothed in formal Niven
outfits and masked so that no part of their bodies are visible. In the center
sits a red mask with an open mouth and closed eyes. To their right is a black
mask with piercing blue eyes, and on the right is a yellow mask with closed eyes
and mouth.
